"""MadGraph gridpack build + lookup for the generation stage.

A gridpack is a relocatable, compile-once MadGraph artifact: the (seed-
independent) process is compiled ONCE into a small tarball, and thereafter every
seed is generated by ``run.sh <nevents> <seed>`` with no recompile. This replaces
the per-seed ``output``+compile, which rebuilt the identical ~30 MB process for
every seed (so N seeds meant N×30 MB and N gfortran builds).

Layout (under ``[output].base``, shared on /blue so every node can read it):

    <output_base>/<proc>/gridpack/<proc>.tar.gz   the gridpack
    <output_base>/<proc>/gridpack/<proc>.sha      hash of the inputs that went
                                                  into it (for invalidation)

Invalidation: the .sha is a hash of ``process.mg5`` + beam energies + the
optional ``run.opts`` + the warmup event count. If any change, the gridpack is
stale and is rebuilt.

MadSpin is not supported via gridpack (MadSpin decays post-generation); a process
carrying a ``madspin.dat`` sidecar falls back to the per-seed ``output`` path.

Build orchestration:
  * ``submit`` pre-builds gridpacks for every process before launching the array
    (one build, on the login node) so array tasks never race to build.
  * an interactive ``run`` builds on demand if missing; a ``run`` inside a SLURM
    array task never builds (it only uses a pre-built gridpack, else falls back).
"""

from __future__ import annotations

import hashlib
import os
import subprocess
from pathlib import Path
from typing import Optional

from delphesprod import cards
from delphesprod.config import Config

DEFAULT_WARMUP = 2000


def _scripts_dir(cfg: Config) -> Path:
    return Path(os.environ.get("DPROD_SCRIPTS_DIR") or (cfg.root / "scripts"))


def warmup_nevents(cfg: Config) -> int:
    return int(cfg.get("gridpack", "warmup", DEFAULT_WARMUP))


def gridpack_dir(cfg: Config, proc: str) -> Path:
    return cfg.output_base / proc / "gridpack"


def tarball(cfg: Config, proc: str) -> Path:
    return gridpack_dir(cfg, proc) / f"{proc}.tar.gz"


def sha_path(cfg: Config, proc: str) -> Path:
    return gridpack_dir(cfg, proc) / f"{proc}.sha"


def supported(proc: str) -> bool:
    """Gridpacks support everything except MadSpin (post-generation decays)."""
    return cards.resolve(proc).madspin is None


def hash_inputs(cfg: Config, proc: str) -> str:
    """Hash the stage-01 inputs baked into a gridpack, for staleness checks."""
    b = cards.resolve(proc)
    beams = cfg.raw.get("beams", {})
    h = hashlib.sha256()
    h.update(b.process.read_bytes())
    h.update(f"ebeam1={beams.get('ebeam1', 6800)};"
             f"ebeam2={beams.get('ebeam2', 6800)};"
             f"warmup={warmup_nevents(cfg)}".encode())
    if b.run_opts and Path(b.run_opts).is_file():
        h.update(b.run_opts.read_bytes())
    return h.hexdigest()


def is_current(cfg: Config, proc: str) -> bool:
    """True iff a gridpack exists and matches the current inputs."""
    tar, sha = tarball(cfg, proc), sha_path(cfg, proc)
    if not (tar.is_file() and tar.stat().st_size > 0 and sha.is_file()):
        return False
    return sha.read_text().strip() == hash_inputs(cfg, proc)


def build(cfg: Config, proc: str, force: bool = False) -> Path:
    """Build (or rebuild) the gridpack for ``proc``; return its path.

    Raises ``GridpackUnsupported`` for MadSpin processes and
    ``subprocess.CalledProcessError`` on a failed MG5 build.
    """
    if not supported(proc):
        raise GridpackUnsupported(
            f"{proc} carries madspin.dat — gridpack not supported, use per-seed compile")
    if not force and is_current(cfg, proc):
        return tarball(cfg, proc)

    env = os.environ.copy()
    env.update(cards.resolve(proc).env())
    script = _scripts_dir(cfg) / "00_gridpack.sh"
    subprocess.run([str(script), proc, str(warmup_nevents(cfg))], env=env, check=True)

    sha_path(cfg, proc).write_text(hash_inputs(cfg, proc) + "\n")
    return tarball(cfg, proc)


def ensure(cfg: Config, proc: str, allow_build: bool = False) -> Optional[Path]:
    """Return a current gridpack path, building it if allowed; else None.

    None means "use the per-seed ``output`` fallback" — either the process is
    MadSpin (unsupported), or no current gridpack exists and building is not
    allowed here (e.g. inside a SLURM array task)."""
    if not supported(proc):
        return None
    if is_current(cfg, proc):
        return tarball(cfg, proc)
    if allow_build:
        return build(cfg, proc, force=True)
    return None


class GridpackUnsupported(RuntimeError):
    """Raised when a gridpack cannot be built for a process (e.g. MadSpin)."""
