#!/bin/bash
# Stage 02: LHE -> Pythia8 shower -> HepMC
#
# Usage: 02_shower.sh <proc> [seed]
# Card:  DPROD_CARD_PYTHIA  (resolved pythia8.cmnd; set by the Python layer)
#
# Reads:  <output_base>/<proc>/lhe/<proc>_seed<seed>.lhe.gz
# Writes: <scratch>/<proc>/hepmc/<proc>_seed<seed>.hepmc.gz

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../setup/env.sh"

PROC="${1:?usage: $0 <proc> [seed]}"
SEED="${2:-1}"

LHE_GZ="$DPROD_OUTPUT_BASE/$PROC/lhe/${PROC}_seed${SEED}.lhe.gz"
[ -f "$LHE_GZ" ] || { echo "no LHE at $LHE_GZ" >&2; exit 1; }

PYCARD="${DPROD_CARD_PYTHIA:?DPROD_CARD_PYTHIA not set (run via the delphesprod CLI)}"
[ -f "$PYCARD" ] || { echo "no Pythia8 card at $PYCARD" >&2; exit 1; }
[ -n "${DPROD_PY8_INTERFACE:-}" ] && [ -x "$DPROD_PY8_INTERFACE" ] || {
  echo "PY8 interface not available; run: delphesprod bootstrap" >&2; exit 1; }

# HepMC + unpacked LHE are bulky throwaways -> scratch (node-local in batch).
HEPDIR="$DPROD_SCRATCH/$PROC/hepmc"
LOGDIR="$DPROD_OUTPUT_BASE/$PROC/logs"
mkdir -p "$HEPDIR" "$LOGDIR"
HEPMC="$HEPDIR/${PROC}_seed${SEED}.hepmc"
LOG="$LOGDIR/02_shower_seed${SEED}.log"

WORK=$(mktemp -d -p "$HEPDIR" shower_XXXXXX)
trap "rm -rf $WORK" EXIT
LHE_PLAIN="$WORK/events.lhe"
zcat "$LHE_GZ" > "$LHE_PLAIN"

# Pythia >=8.310 rejects `Main:numberOfEvents = -1` ("out of range"), unlike the
# 8.306 the original tree shipped. Set the exact LHE event count instead — this
# is version-robust and also avoids the interface's 1000-event default
# over-running a short LHE.
NEV=$(grep -c '<event>' "$LHE_PLAIN" 2>/dev/null || echo 0)
[ "$NEV" -gt 0 ] || { echo "[02_shower] no <event> tags in LHE $LHE_PLAIN" >&2; exit 1; }
echo "[02_shower] LHE has $NEV events"

CMND="$WORK/pythia.cmnd"
cat > "$CMND" <<EOF
! Auto-generated by 02_shower.sh
! HEPMCoutput:file and LHEFInputs:nSubruns are read globally by the
! MG5aMC_PY8_interface. Beam settings go inside Main:subrun = 0
! (the interface loops iRun in [0, nSubruns)).
HEPMCoutput:file       = $HEPMC
LHEFInputs:nSubruns    = 1
Main:numberOfEvents    = $NEV
Main:timesAllowErrors  = 100

Main:subrun            = 0
Beams:frameType        = 4
Beams:LHEF             = $LHE_PLAIN

$(cat "$PYCARD")
EOF

echo "[02_shower] running MG5aMC_PY8_interface ($PROC, seed=$SEED, log=$LOG)"
"$DPROD_PY8_INTERFACE" "$CMND" > "$LOG" 2>&1 || {
  echo "[02_shower] Pythia8 failed; tail of log:" >&2
  tail -40 "$LOG" >&2
  exit 1
}

[ -s "$HEPMC" ] || { echo "[02_shower] HepMC output empty: $HEPMC" >&2; exit 1; }
gzip -f "$HEPMC"
echo "[02_shower] wrote ${HEPMC}.gz"
